openapi: 3.0.0
info:
  title: Todo List API
  version: 1.0.0
  description: API documentation for the Todo List application
tags:
  - name: Authentication
    description: User authentication management

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - nickname
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                nickname:
                  type: string
      responses:
        200:
          description: User created successfully
        400:
          description: Bad request
        500:
          description: Internal server error

  /auth/login:
    post:
      summary: Log in with email and password
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /auth/google:
    post:
      summary: Authenticate using Google
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - idToken
              properties:
                idToken:
                  type: string
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
